image: haskell:9.8.4

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache:
  paths:
    - .stack
    - .stack-work

before_script:
  - stack config set system-ghc --global true

build:
  stage: build
  script:
    - stack --no-terminal build

test:
  before_script:
    - apt-get update -yqq
    - apt-get install -y graphviz
  script:
    - stack --no-terminal test --coverage --haddock --no-haddock-deps
  coverage: '/(\d+)% top-level declarations used/'
  after_script:
    - rm -rf ./hpc
    - mv .stack-work/install/*/*/*/hpc ./hpc
  artifacts:
    paths:
      - "hpc/"
  cache:
    policy: pull

hlint:
  image: debian:stable
  before_script:
    - apt-get update -yqq
    - apt-get install -y curl
  stage: build
  script:
    - curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
  cache:
    policy: pull
